### ISSUE TITLE
AttributeError: module 'osgeo.osr' has no attribute 'GetPROJVersionMajor'

### ISSUE THREAD

**Issue by SrNetoChan** [GispoCoding/GlobeBuilder#18]
I got this error when using QGIS 3.10.11 in Kubuntu 18.04.

2020-11-15T00:42:03     WARNING    Traceback (most recent call last):
              File "/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GlobeBuilder/plugin.py", line 211, in run
              self.dockwidget = GlobeBuilderDockWidget(self.iface)
              File "/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GlobeBuilder/ui/globe_builder_dockwidget.py", line 85, in __init__
              self.populate_comboBoxProjections()
              File "/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GlobeBuilder/ui/globe_builder_dockwidget.py", line 245, in populate_comboBoxProjections
              proj_v = proj_version()
              File "/home/aneto/.local/share/QGIS/QGIS3/profiles/default/python/plugins/GlobeBuilder/qgis_plugin_tools/tools/version.py", line 29, in proj_version
              major: int = osr.GetPROJVersionMajor()
             AttributeError: module 'osgeo.osr' has no attribute 'GetPROJVersionMajor'

**Comment by Joonalai** [comment]
Thank you for reporting the issue!

**Comment by SrNetoChan** [comment]
Thanks for your plugin :-)
