### ISSUE TITLE
Geocoding seems to be broken - May 2024

### ISSUE THREAD

**Issue by alasdairrae** [GispoCoding/GlobeBuilder#24]
**When I search for a place using the Geocoding option and then hit search I get no results. Previously this worked fine for me.**
![globe-builder-geocoding](https://github.com/GispoCoding/GlobeBuilder/assets/12211470/bae4599c-1a19-43a1-a498-128e99716c0f)

Is the connection to the Nominatum API somehow broken? 

I have heard from another user of the plugin that they are having the same issue so I am reporting this here in the hope that it could be fixed or a solution found.

Thanks.

**Comment by lehtojaa** [comment]
I can confirm the bug, and after a quick glance, it seems to be related to an outdated form of the url the plugin uses in the geocoding query. See, for example: [link](https://nominatim.openstreetmap.org/search/helsinki?limit=5&format=geojson) 

Here is the error message for my case:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users/Jaakko/AppData/Roaming/QGIS/QGIS3\profiles\globe_builder_dev/python/plugins\GlobeBuilder\core\utils\geocoder.py", line 80, in on_search_response
    LOGGER.warning(str(error))
Message: '203'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\Users/Jaakko/AppData/Roaming/QGIS/QGIS3\profiles\globe_builder_dev/python/plugins\GlobeBuilder\core\utils\geocoder.py", line 81, in on_search_response
    LOGGER.warning(search_result.errorString())
Message: 'Error transferring https://nominatim.openstreetmap.org/search/helsinki?limit=5&format=geojson - server replied: Not Found'
Arguments: ()
```
